SOURCE: SYNTHETIC
DATA_DIRECTORY_SOURCE: "../../data/synthetic_smoke"
DATA_LIST_SOURCE: '../dataset/synthetic_smoke_list/{}.txt'

TARGET: REAL
DATA_DIRECTORY_TARGET: "../../data/real_smoke"
DATA_LIST_TARGET: '../dataset/real_smoke_list/{}.txt'

EXP_NAME: SYNTHETIC2REAL_DeepLabv2_AdvEnt_2x_entropy
NUM_CLASSES: 2
NUM_WORKERS: 4
TRAIN:

  SET_SOURCE: 'all'
  MAX_ITERS: 250000
  EARLY_STOP: 6000
  BATCH_SIZE_SOURCE: 2
  INPUT_SIZE_SOURCE: [1024, 512] 
  IMG_MEAN: [122, 122, 122]
  SAVE_PRED_EVERY: 2000
  
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2
  RESTORE_FROM: ../../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.002
  LAMBDA_ADV_AUX: 0.0004
TEST:
  MODE: best